### ISSUE TITLE
Paginator - Make recordsPerPage property as Input value to set it manually

### ISSUE THREAD

**Issue by IraErshova** [GetTerminus/terminus-oss#343]
### Is your feature request related to a problem? Please describe.

There is a case when a developer wants to use different from 10 (**DEFAULT_RECORDS_PER_PAGE**) value. The only possible way to do this is to use ViewChild. Another case when the developer uses custom **recordsPerPageChoices** and 10 is not included in this array. That leads to the issue.

### Describe the solution you'd like.

Make **recordsPerPage** as Input value so that developers can set up the initial value depends on their requirements. Always check if this value is included in **recordsPerPageChoices** array. If there is no **recordsPerPage** then use the first value from **recordsPerPageChoices** or **DEFAULT_RECORDS_PER_PAGE**.

### Describe alternatives you've considered

> A clear and concise description of any alternative solutions or features you've considered.

### Additional context

> Add any other context or screenshots about the feature request here.

**Comment by benjamincharity** [comment]
On hold since paginator is about to get a rewrite

**Comment by benjamincharity** [comment]
Closing as the per page selector is being removed https://github.com/GetTerminus/terminus-oss/issues/412
