### ISSUE TITLE
Paginator - recordsPerPageChange has wrong type for emitted event

### ISSUE THREAD

**Issue by IraErshova** [GetTerminus/terminus-oss#345]
#### 1. What is the expected behavior?
recordsPerPageChange emits an event with type - **[number]** (e.g. [50] or [20]) that's why expected type - **EventEmitter<[number]>**

#### 2. What is the current behavior?
recordsPerPageChange has type - **EventEmitter\<number\>**

#### 3. What are the steps to reproduce?
1. Open demo app
http://uilibrary-docs.terminus.ninja/release/components/TsPaginatorComponent.html#example
2. Open browser's console
3. Change records per page and check the result in the console

> Providing a reproduction is the *best* way to share your issue.

#### 4. Provide environment information

- Package(s) + version: "@terminus/ui-paginator": "^2.0.6",
- Angular: "@angular/core": "^9.1.0",
- TypeScript: "3.7.5"
- Browser(s): Google Chrome 85.0.4183.102 (Official Build) (64-bit)

#### 5. Is there anything else we should know?

There are 2 ways to resolve this issue:
1. Change typing
2. Change emitted value

**Comment by IraErshova** [comment]
@benjamincharity Hey! PR, which you've linked to this issue doesn't fix the problem. Do you want me to add the fix into my PR?

**Comment by benjamincharity** [comment]
ahh whoops! If you don't mind, that would be greatly appreciated!!
